adjust commands

diff --git a/.github/workflows/wf_sf_objects.yml b/.github/workflows/wf_sf_objects.yml
--- a/.github/workflows/wf_sf_objects.yml
+++ b/.github/workflows/wf_sf_objects.yml
@@ -22,6 +22,28 @@ jobs:
         run: |
           curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.3/linux_x86_64/snowsql-1.3.0-linux_x86_64.bash
           SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.3.0-linux_x86_64.bash
+      - name: Check Exist Target Star Schema
+        run: |
+          if [[ ${{ github.repository }} != "RepoED" ]] && [[ -z ${{ vars.TARGET_STAR_SCHEMA }} ]]; then
+            echo "Error: Repository is not 'RepoED, but  we don't have repo variable TARGET_STAR_SCHEMA!"
+            exit 1
+          fi
+      - name: Get Unique Identifiers
+        id: extract-unique-identifiers
+        run: |
+          if [[ -n $TARGET_STAR_SCHEMA ]]; then
+            unique_identifiers=("CONFORMEDDIM" "$TARGET_STAR_SCHEMA")
+          else
+            identifiers=()
+            # for file in $(find ${{ github.workspace }}/snowflake_objects -type f -name '*.sql'); do 
+            for file in ${{ github.workspace }}/snowflake_objects/*.sql; do
+              if [[ $file =~ ^.*_(.*)\.sql$ ]]; then
+                identifiers+=("${BASH_REMATCH[1]}")
+              fi
+            done
+            unique_identifiers=($(echo "${identifiers[@]}" | tr ' ' '\n' | sort -u))
+          fi
+          echo "::set-output name=identifiers::${identifiers[*]}"
       - name: Deploy
         env:
           SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
@@ -38,20 +60,7 @@ jobs:
           ~/bin/snowsql -q "$ddl_master_change_history_query"        
           pip install schemachange==3.6.1
 
-          if [[ -n $TARGET_STAR_SCHEMA ]]; then
-            unique_identifiers=("CONFORMEDDIM" "$TARGET_STAR_SCHEMA")
-          else
-            identifiers=()
-            # for file in $(find ${{ github.workspace }}/snowflake_objects -type f -name '*.sql'); do 
-            for file in ${{ github.workspace }}/snowflake_objects/*.sql; do
-              if [[ $file =~ ^.*_(.*)\.sql$ ]]; then
-                identifiers+=("${BASH_REMATCH[1]}")
-              fi
-            done
-            unique_identifiers=($(echo "${identifiers[@]}" | tr ' ' '\n' | sort -u))
-          fi
-
-          for identifier in "${unique_identifiers[@]}"; do
+          for identifier in "${steps.extract-unique-identifiers.outputs.unique_identifiers[@]}"; do
             echo "Execute identifier $identifier!"
             mkdir ${{ github.workspace }}/snowflake_objects/folder_tmp
             cp ${{ github.workspace }}/snowflake_objects/*_$identifier.sql ${{ github.workspace }}/snowflake_objects/folder_tmp
@@ -65,78 +74,3 @@ jobs:
             ~/bin/snowsql -q "$dml_change_history_query"
             rm -rf ${{ github.workspace }}/snowflake_objects/folder_tmp    
           done
-
-
-
-
-
-          # echo "Execute conformed dims first!"
-          # mkdir ${{ github.workspace }}/snowflake_objects/folder_tmp
-          # cp ${{ github.workspace }}/snowflake_objects/*_CONFORMEDDIM.sql ${{ github.workspace }}/snowflake_objects/folder_tmp
-          # ddl_project_change_history_query=$(cat "$GITHUB_WORKSPACE/snowflake_objects/change_history/ddl_project_change_history.sql" | sed "s/{TARGET_STAR_SCHEMA}/CONFORMEDDIM/g")
-          # echo "$ddl_project_change_history_query"
-          # ~/bin/snowsql -q "$ddl_project_change_history_query"          
-          # schemachange -f $GITHUB_WORKSPACE/snowflake_objects/folder_tmp -a $SNOWSQL_ACCOUNT -u $SNOWSQL_USER -r $SNOWSQL_ROLE -w $SNOWSQL_WAREHOUSE -d $SNOWSQL_DATABASE -c $SNOWSQL_DATABASE.SCHEMACHANGE.CHANGE_HISTORY_CONFORMEDDIM
-          # # merge project change history into master change history table
-          # # finally drop project change history table
-          # dml_change_history_query=$(cat "$GITHUB_WORKSPACE/snowflake_objects/change_history/dml_change_history.sql" | sed "s/{TARGET_STAR_SCHEMA}/CONFORMEDDIM/g")
-          # echo "$dml_change_history_query"
-          # ~/bin/snowsql -q "$dml_change_history_query"
-          # rm -rf ${{ github.workspace }}/snowflake_objects/folder_tmp          
-
-          # echo "Execute target star schema then!"
-          # mkdir ${{ github.workspace }}/snowflake_objects/folder_tmp
-          # cp ${{ github.workspace }}/snowflake_objects/*_$TARGET_STAR_SCHEMA.sql ${{ github.workspace }}/snowflake_objects/folder_tmp
-          # ddl_project_change_history_query=$(cat "$GITHUB_WORKSPACE/snowflake_objects/change_history/ddl_project_change_history.sql" | sed "s/{TARGET_STAR_SCHEMA}/$TARGET_STAR_SCHEMA/g")
-          # echo "$ddl_project_change_history_query"
-          # ~/bin/snowsql -q "$ddl_project_change_history_query"          
-          # schemachange -f $GITHUB_WORKSPACE/snowflake_objects/folder_tmp -a $SNOWSQL_ACCOUNT -u $SNOWSQL_USER -r $SNOWSQL_ROLE -w $SNOWSQL_WAREHOUSE -d $SNOWSQL_DATABASE -c $SNOWSQL_DATABASE.SCHEMACHANGE.CHANGE_HISTORY_$TARGET_STAR_SCHEMA
-          # # finally drop project change history table
-          # dml_change_history_query=$(cat "$GITHUB_WORKSPACE/snowflake_objects/change_history/dml_change_history.sql" | sed "s/{TARGET_STAR_SCHEMA}/$TARGET_STAR_SCHEMA/g")
-          # echo "$dml_change_history_query"
-          # ~/bin/snowsql -q "$dml_change_history_query"
-          # rm -rf ${{ github.workspace }}/snowflake_objects/folder_tmp       
-
-
-          # abc
-
-
-          # if [[ -n $TARGET_STAR_SCHEMA ]]; then
-          #   # if this job runs at project repo
-          #   # only run the target project subdirectory and skip the other subdirectories
-          #   echo "Target STAR SCHEMA is $TARGET_STAR_SCHEMA!"
-
-          #   mkdir ${{ github.workspace }}/objects/folder_tmp
-          #   cp ${{ github.workspace }}/objects/*__$TARGET_STAR_SCHEMA_* ${{ github.workspace }}/objects/folder_tmp
-          #   ddl_project_change_history_query=$(cat "$GITHUB_WORKSPACE/objects/change_history/ddl_project_change_history.sql" | sed "s/{TARGET_STAR_SCHEMA}/$TARGET_STAR_SCHEMA/g")
-          #   echo "$ddl_project_change_history_query"
-          #   ~/bin/snowsql -q "$ddl_project_change_history_query"
-
-          #   schemachange -f $GITHUB_WORKSPACE/objects/folder_tmp -a $SNOWSQL_ACCOUNT -u $SNOWSQL_USER -r $SNOWSQL_ROLE -w $SNOWSQL_WAREHOUSE -d $SNOWSQL_DATABASE -c $SNOWSQL_DATABASE.SCHEMACHANGE.CHANGE_HISTORY_$TARGET_STAR_SCHEMA
-            
-          #   # merge project change history into master change history table
-          #   # finally drop project change history table
-          #   dml_change_history_query=$(cat "$GITHUB_WORKSPACE/objects/change_history/dml_change_history.sql" | sed "s/{TARGET_STAR_SCHEMA}/$TARGET_STAR_SCHEMA/g")
-          #   echo "$dml_change_history_query"
-          #   ~/bin/snowsql -q "$dml_change_history_query"
-          #   rm -rf ${{ github.workspace }}/objects/folder_tmp          
-
-          # else
-          #   # if this job runs at ED repo
-          #   # loop through all subdirectories for all projects
-          #   for dir in "$GITHUB_WORKSPACE/objects"/*/; do
-          #     subdir=$(basename "$dir")
-          #     echo "Found project subdirectory: $subdir"
-          #     # create change history table for project if not exists
-          #     ddl_project_change_history_query=$(cat "$GITHUB_WORKSPACE/objects/ddl_project_change_history.sql" | sed "s/{PROJECT}/$subdir/g")
-          #     echo "$ddl_project_change_history_query"
-          #     ~/bin/snowsql -q "$ddl_project_change_history_query"
-          #     # run schemachange
-          #     schemachange -f $GITHUB_WORKSPACE/objects/$subdir -a $SNOWSQL_ACCOUNT -u $SNOWSQL_USER -r $SNOWSQL_ROLE -w $SNOWSQL_WAREHOUSE -d $SNOWSQL_DATABASE -c $SNOWSQL_DATABASE.SCHEMACHANGE.CHANGE_HISTORY_$subdir 
-          #     # merge project change history into master change history table
-          #     # finally drop project change history table
-          #     dml_change_history_query=$(cat "$GITHUB_WORKSPACE/objects/dml_change_history.sql" | sed "s/{PROJECT}/$subdir/g")
-          #     echo "$dml_change_history_query"
-          #     ~/bin/snowsql -q "$dml_change_history_query"
-          #   done
-          # fi
